//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoApplyConfig) DeepCopyInto(out *AutoApplyConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoApplyConfig.
func (in *AutoApplyConfig) DeepCopy() *AutoApplyConfig {
	if in == nil {
		return nil
	}
	out := new(AutoApplyConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AutoApplyConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoApplyConfigList) DeepCopyInto(out *AutoApplyConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AutoApplyConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoApplyConfigList.
func (in *AutoApplyConfigList) DeepCopy() *AutoApplyConfigList {
	if in == nil {
		return nil
	}
	out := new(AutoApplyConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AutoApplyConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoApplyConfigSpec) DeepCopyInto(out *AutoApplyConfigSpec) {
	*out = *in
	if in.ExcludePods != nil {
		in, out := &in.ExcludePods, &out.ExcludePods
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ExcludeNamespaces != nil {
		in, out := &in.ExcludeNamespaces, &out.ExcludeNamespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoApplyConfigSpec.
func (in *AutoApplyConfigSpec) DeepCopy() *AutoApplyConfigSpec {
	if in == nil {
		return nil
	}
	out := new(AutoApplyConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoApplyConfigStatus) DeepCopyInto(out *AutoApplyConfigStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoApplyConfigStatus.
func (in *AutoApplyConfigStatus) DeepCopy() *AutoApplyConfigStatus {
	if in == nil {
		return nil
	}
	out := new(AutoApplyConfigStatus)
	in.DeepCopyInto(out)
	return out
}
